server:
  port: 8335

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/tek_micro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}  # Enforces a stable identity: order-service:8335
    prefer-ip-address: true                                 # Resolves via IP instead of machine hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      userServiceBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    retryAspectOrder: 2
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - feign.FeignException
          - java.io.IOException

  ratelimiter:
    instances:
      orderRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0ms